services:
  - type: web
    name: sistema-egresados-umb
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: TELEGRAM_TOKEN
        value: 8228079798:AAGQdTst1MuV3V1sV_4ApPphgEg7dzEHYac
      - key: SECRET_KEY
        value: umb-egresados-2025-clave-segura-12345
      - key: DEBUG
        sync: false
      - key: DATABASE_URL
        value: postgresql://egresados_umb_db_user:hHE0nFUU1jsz8stqhUGb3s4m2EQI4A82@dpg-d5kjdcnfte5s73cmmdu0-a/egresados_umb_db